### ISSUE TITLE
Custom Icon With Overlay

### ISSUE THREAD

**Issue by boomshroom** [Rycieos/factorio-colorblind-ultimate#4]
### Description

Give the option to have both an overlay and a custom icon at the same time, rather than needing to choose one or the other.

### Details

Currently, you can only choose between a custom icon, a text overlay, or an icon overlay. The custom icons for, for example, the transport belts, are nice, but they aren't available for all belt-related items. For the ones where there isn't (or doesn't make as much sense to be) a custom icon, you need to resort to a tier overlay icon. This however means that, for example, the splitters have tier icons, but the undergrounds don't, and you can't give them tier icons without giving up the custom sprite. This incongruity can be rather jarring.

(A distinct but related issue is for items with multiple overlays where they can either both be icons or both be text, but not mix and match. For me this is mainly for the explosive uranium cannon shells, where I've generally used the text overlay for explosive variants, but the icon overlay for other uranium products.)

### Suggested solution

Probably give separate settings for items and entities with custom icons where they can be selected, while the existing settings only set the overlay they have.

**Comment by Rycieos** [comment]
Thanks for the suggestions!

This would balloon the possible options a ton. Where there are currently 7 options, it would increase that to... I won't even do the math, but it would be not feasible.

I think the only way to this would be to change the current system, where you get an option named "Underground belt" and currently your options are:
* None
* Custom icon
* Custom icon and entity
* Custom entity sprite
* Tier overlay
* Tier overlay icon only
* Tier overlay entity only

To having 4 checkbox options:
* Underground belt custom icon
* Underground belt custom entity sprite
* Underground belt tier overlay icon
* Underground belt tier overlay entity sprite

Then you can mix and match as much as you want. This would obviously make the options page even longer. How does that sound?


Then for the second issue, I could make options like this for Explosive uranium cannon shells:
* Explosive uranium cannon shell: nuclear icon overlay (options none, icon, text)
* Explosive uranium cannon shell: explosive icon overlay (options none, icon, text)

Thoughts?

**Comment by Rycieos** [comment]
I have a prototype build, if you would be willing to test it and let me know what you think: 
[colorblind_ultimate_1.6.0.zip](https://github.com/user-attachments/files/17283046/colorblind_ultimate_1.6.0.zip)

As for the Explosive uranium cannon shells, I have realized that that is the *only* item that has multiple text icons on it. (Stack filter inserter has 2 icons, but only 1 text icon. And it is going away in the expansion IIRC.) Maybe the better solution is to create one text icon for it? Either `UEx` or `ExU` ?

**Comment by boomshroom** [comment]
I personally don't really see why someone would want tier icons on only some tiers of a given set rather than all of them, but I also can't see how to provide said options without the explosion of settings you mentioned. I'll definitely try out the changes in that build! Thank you!
